//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MurtiWifiConnecter.Properties {
    using System;
    using System.Reflection;
    using System.Resources;
    using System.Globalization;
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;
        
        public Resources() {}
        
        public static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new ResourceManager("MurtiWifiConnecter.Resources.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }
        
        public static CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
        
        public static string AvailableNetworks {
            get { return ResourceManager.GetString("AvailableNetworks", resourceCulture); }
        }
        public static string Connect {
            get { return ResourceManager.GetString("Connect", resourceCulture); }
        }
        public static string PasswordPlaceholder {
            get { return ResourceManager.GetString("PasswordPlaceholder", resourceCulture); }
        }
        public static string RefreshNetworks {
            get { return ResourceManager.GetString("RefreshNetworks", resourceCulture); }
        }
        // 他のリソースキーも同様に追加可能
    }
}
