<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <RootNamespace>MWC.Platform.Windows</RootNamespace>
    <AssemblyName>MWC.Platform.Windows</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MWC.Core\MWC.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ManagedNativeWifi" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" />
  </ItemGroup>
</Project>
