#!/usr/bin/env pwsh
<#
.SYNOPSIS
    IEEE OUI データベースを取得し、OuiLookupService.cs の BuildDatabase() を更新する。
.DESCRIPTION
    IEEE Std 802-2014 公開 OUI リスト (oui.txt) をダウンロードし、
    MWC.Core の OuiLookupService.cs 内蔵 DB をアップデートする。
    GitHub Actions の schedule で月 1 回自動実行可能。

.EXAMPLE
    .\oui-update.ps1
    .\oui-update.ps1 -MaxEntries 5000 -OutputPath .\OuiDb.cs
#>
[CmdletBinding()]
param(
    [string]$OuiTxtUrl  = "https://standards-oui.ieee.org/oui/oui.txt",
    [int]   $MaxEntries = 3000,
    [string]$OutputPath = ".\src\MWC.Core\Services\OuiLookupService.cs"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

Write-Host "Downloading OUI database..."
$raw = (Invoke-WebRequest -Uri $OuiTxtUrl -UseBasicParsing).Content

# "XX-XX-XX   (hex)   Vendor Name" 行をパース
$entries = [System.Collections.Generic.Dictionary[string,string]]::new()
foreach ($line in ($raw -split "`n"))
{
    if ($line -match "^([0-9A-F]{2}-[0-9A-F]{2}-[0-9A-F]{2})\s+\(hex\)\s+(.+)$")
    {
        $oui    = $Matches[1].Replace("-","")
        $vendor = $Matches[2].Trim()
        if (-not $entries.ContainsKey($oui))
        {
            $entries[$oui] = $vendor
            if ($entries.Count -ge $MaxEntries) { break }
        }
    }
}
Write-Host "Parsed $($entries.Count) OUI entries."

# C# コード生成
$sb = [System.Text.StringBuilder]::new()
$sb.AppendLine("// AUTO-GENERATED by tools/oui-update.ps1 on $(Get-Date -Format 'yyyy-MM-dd'). DO NOT EDIT MANUALLY.")
$sb.AppendLine("// Source: IEEE OUI Database")
$sb.AppendLine("")
$sb.AppendLine("using System;")
$sb.AppendLine("using System.Collections.Frozen;")
$sb.AppendLine("using System.Collections.Generic;")
$sb.AppendLine("")
$sb.AppendLine("namespace MWC.Core.Services;")
$sb.AppendLine("")
$sb.AppendLine("public sealed partial class OuiLookupService")
$sb.AppendLine("{")
$sb.AppendLine("    private static Dictionary<string, string> BuildDatabase() => new(StringComparer.OrdinalIgnoreCase)")
$sb.AppendLine("    {")

foreach ($kv in $entries.GetEnumerator())
{
    $escaped = $kv.Value.Replace('"', '\"')
    $sb.AppendLine("        [`"$($kv.Key)`"] = `"$escaped`",")
}

$sb.AppendLine("    };")
$sb.AppendLine("}")

Set-Content -Path $OutputPath -Value $sb.ToString() -Encoding utf8
Write-Host "Written to $OutputPath"
